/*
 * Creative Library Demo-Daten
 * Liefert ein Set an Creatives, das die Overthrow-Doku widerspiegelt.
 */

export function getDemoCreatives() {
  return [
    {
      id: 1,
      title: "Mia_Hook_Problem_Solution_v3",
      creator: "Mia",
      type: "video",
      tags: ["Winner", "UGC"],
      status: "active",
      roas: 6.8,
      spend: 12340,
      ctr: 0.041,
      cpm: 7.2,
      impressions: 172000,
      daysRunning: 12,
      hook: "Problem/Solution",
      campaignName: "UGC Scale Test",
    },
    {
      id: 2,
      title: "Tom_Testimonial_ShortForm_v1",
      creator: "Tom",
      type: "video",
      tags: ["Winner"],
      status: "active",
      roas: 5.9,
      spend: 8400,
      ctr: 0.038,
      cpm: 7.8,
      impressions: 136000,
      daysRunning: 9,
      hook: "Testimonial",
      campaignName: "UGC Scale Test",
    },
    {
      id: 3,
      title: "Lisa_BeforeAfter_Showcase_v2",
      creator: "Lisa",
      type: "video",
      tags: ["Winner"],
      status: "active",
      roas: 5.2,
      spend: 6100,
      ctr: 0.035,
      cpm: 7.1,
      impressions: 92000,
      daysRunning: 11,
      hook: "Before/After",
      campaignName: "Conversion Boost",
    },
    {
      id: 4,
      title: "Generic_Product_Static_v12",
      creator: "Stock",
      type: "static",
      tags: ["Loser"],
      status: "paused",
      roas: 1.2,
      spend: 3200,
      ctr: 0.009,
      cpm: 9.8,
      impressions: 325000,
      daysRunning: 21,
      hook: "Direct CTA",
      campaignName: "Brand Awareness",
    },
    {
      id: 5,
      title: "Mia_Problem_Solution_v4",
      creator: "Mia",
      type: "video",
      tags: ["Testing", "UGC"],
      status: "testing",
      roas: 4.2,
      spend: 2400,
      ctr: 0.038,
      cpm: 7.5,
      impressions: 51000,
      daysRunning: 4,
      hook: "Problem/Solution",
      campaignName: "Testing: Hook Battle",
    },
    {
      id: 6,
      title: "Tom_Testimonial_LongForm_v2",
      creator: "Tom",
      type: "video",
      tags: ["Testing"],
      status: "testing",
      roas: 3.1,
      spend: 2100,
      ctr: 0.024,
      cpm: 8.3,
      impressions: 72000,
      daysRunning: 5,
      hook: "Testimonial",
      campaignName: "Testing: Hook Battle",
    },
    {
      id: 7,
      title: "Lisa_Static_BeforeAfter_v1",
      creator: "Lisa",
      type: "static",
      tags: ["Testing", "Static"],
      status: "active",
      roas: 3.4,
      spend: 1800,
      ctr: 0.028,
      cpm: 7.9,
      impressions: 64000,
      daysRunning: 7,
      hook: "Before/After",
      campaignName: "Retargeting Cold",
    },
    {
      id: 8,
      title: "UGC_Founder_Story_v1",
      creator: "Founder",
      type: "video",
      tags: ["Testing", "UGC"],
      status: "active",
      roas: 4.9,
      spend: 3900,
      ctr: 0.036,
      cpm: 8.0,
      impressions: 98000,
      daysRunning: 6,
      hook: "Story",
      campaignName: "Brand Storytelling",
    },
  ];
}
